/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as AtletasIndexRouteImport } from './routes/atletas.index'
import { Route as AtletasAthleteIdRouteImport } from './routes/atletas.$athleteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasIndexRoute = AtletasIndexRouteImport.update({
  id: '/atletas/',
  path: '/atletas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasAthleteIdRoute = AtletasAthleteIdRouteImport.update({
  id: '/atletas/$athleteId',
  path: '/atletas/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/atletas/$athleteId': typeof AtletasAthleteIdRoute
  '/atletas/': typeof AtletasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/atletas/$athleteId': typeof AtletasAthleteIdRoute
  '/atletas': typeof AtletasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/atletas/$athleteId': typeof AtletasAthleteIdRoute
  '/atletas/': typeof AtletasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipes' | '/atletas/$athleteId' | '/atletas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipes' | '/atletas/$athleteId' | '/atletas'
  id: '__root__' | '/' | '/equipes' | '/atletas/$athleteId' | '/atletas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipesRoute: typeof EquipesRoute
  AtletasAthleteIdRoute: typeof AtletasAthleteIdRoute
  AtletasIndexRoute: typeof AtletasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/': {
      id: '/atletas/'
      path: '/atletas'
      fullPath: '/atletas/'
      preLoaderRoute: typeof AtletasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/$athleteId': {
      id: '/atletas/$athleteId'
      path: '/atletas/$athleteId'
      fullPath: '/atletas/$athleteId'
      preLoaderRoute: typeof AtletasAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipesRoute: EquipesRoute,
  AtletasAthleteIdRoute: AtletasAthleteIdRoute,
  AtletasIndexRoute: AtletasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
