/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as AtletasIndexRouteImport } from './routes/atletas.index'
import { Route as AtletasAthleteIdRouteImport } from './routes/atletas.$athleteId'
import { Route as PartidasIndexRouteImport } from './routes/partidas.index'
import { Route as PartidasMatchIdRouteImport } from './routes/partidas.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasIndexRoute = AtletasIndexRouteImport.update({
  id: '/atletas/',
  path: '/atletas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtletasAthleteIdRoute = AtletasAthleteIdRouteImport.update({
  id: '/atletas/$athleteId',
  path: '/atletas/$athleteId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasIndexRoute = PartidasIndexRouteImport.update({
  id: '/partidas/',
  path: '/partidas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidasMatchIdRoute = PartidasMatchIdRouteImport.update({
  id: '/partidas/$matchId',
  path: '/partidas/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/atletas/$athleteId': typeof AtletasAthleteIdRoute
  '/partidas/$matchId': typeof PartidasMatchIdRoute
  '/atletas/': typeof AtletasIndexRoute
  '/partidas/': typeof PartidasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/atletas/$athleteId': typeof AtletasAthleteIdRoute
  '/partidas/$matchId': typeof PartidasMatchIdRoute
  '/atletas': typeof AtletasIndexRoute
  '/partidas': typeof PartidasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipes': typeof EquipesRoute
  '/atletas/$athleteId': typeof AtletasAthleteIdRoute
  '/partidas/$matchId': typeof PartidasMatchIdRoute
  '/atletas/': typeof AtletasIndexRoute
  '/partidas/': typeof PartidasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/equipes'
    | '/atletas/$athleteId'
    | '/partidas/$matchId'
    | '/atletas/'
    | '/partidas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/equipes'
    | '/atletas/$athleteId'
    | '/partidas/$matchId'
    | '/atletas'
    | '/partidas'
  id:
    | '__root__'
    | '/'
    | '/equipes'
    | '/atletas/$athleteId'
    | '/partidas/$matchId'
    | '/atletas/'
    | '/partidas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipesRoute: typeof EquipesRoute
  AtletasAthleteIdRoute: typeof AtletasAthleteIdRoute
  PartidasMatchIdRoute: typeof PartidasMatchIdRoute
  AtletasIndexRoute: typeof AtletasIndexRoute
  PartidasIndexRoute: typeof PartidasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/': {
      id: '/atletas/'
      path: '/atletas'
      fullPath: '/atletas/'
      preLoaderRoute: typeof AtletasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletas/$athleteId': {
      id: '/atletas/$athleteId'
      path: '/atletas/$athleteId'
      fullPath: '/atletas/$athleteId'
      preLoaderRoute: typeof AtletasAthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/': {
      id: '/partidas/'
      path: '/partidas'
      fullPath: '/partidas/'
      preLoaderRoute: typeof PartidasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partidas/$matchId': {
      id: '/partidas/$matchId'
      path: '/partidas/$matchId'
      fullPath: '/partidas/$matchId'
      preLoaderRoute: typeof PartidasMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipesRoute: EquipesRoute,
  AtletasAthleteIdRoute: AtletasAthleteIdRoute,
  PartidasMatchIdRoute: PartidasMatchIdRoute,
  AtletasIndexRoute: AtletasIndexRoute,
  PartidasIndexRoute: PartidasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
